export const ROLE = {
    TECH_OWNER: 0,
    OWNER: 2,
    PSICOLOGO: 4,
    SECRETARIA: 6
};

export const NAV_PERMISSIONS = {
    MASTER: [ROLE.TECH_OWNER, ROLE.OWNER],
    PROFESSIONAL: [ROLE.TECH_OWNER, ROLE.OWNER, ROLE.PSICOLOGO],
    PUBLIC: [ROLE.TECH_OWNER, ROLE.OWNER, ROLE.PSICOLOGO, ROLE.SECRETARIA]
};

export const ACTION_PERMISSIONS = {
    // Quién puede crear pacientes desde cero
    CREATE_PATIENT: [ROLE.TECH_OWNER, ROLE.OWNER, ROLE.SECRETARIA, ROLE.PSICOLOGO],
    // Quién puede escribir notas clínicas (Solo dueños de registro o perfiles médicos)
    WRITE_CLINICAL_NOTES: [ROLE.TECH_OWNER, ROLE.OWNER, ROLE.PSICOLOGO],
    // Quién puede ver la lista general
    VIEW_PATIENTS_LIST: [ROLE.TECH_OWNER, ROLE.OWNER, ROLE.PSICOLOGO, ROLE.SECRETARIA]
};